# Exercises (Optional)

These exercises are not required to complete however are good to do for practice. (Not to be submitted on git)

These exercises are a mix of Python and pandas/EDA practice. Most should be no more than a few lines of code! 

In [15]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a
print(a[3:6])
# reverse the list
print(a[5::-1])
# get a list where each entry in a is squared (so the new list is [1, 4, 9, 16, 25, 36])
l =[]
for i in a:
    l.append(i**2)
print(l)

[4, 5, 6]
[6, 5, 4, 3, 2, 1]
[1, 4, 9, 16, 25, 36]


In [17]:
import numpy as np
# create a numpy array from this list
b = np.array(a) # change this

In [18]:
# find the mean of b
np.mean(b)

3.5

In [19]:
# get a list where each entry in b is squared (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
np.square(b)

array([ 1,  4,  9, 16, 25, 36])

In [26]:
# change b from a length-6 list to a 2x3 matrix
b = np.reshape(b, (2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# find the mean value of each row
np.mean(b, 0)
np.mean(b, 1)

array([2., 5.])

In [29]:
# find the mean value of each column
column_mean = b.mean(axis=0)
column_mean

array([2.5, 3.5, 4.5])

In [36]:
# find the third column of b
arr = []
for i in b:
    arr.append(i[2])
arr


[3, 6]

In [6]:
# load in the "starbucks.csv" dataset
import pandas as pd
df = pd.read_csv("../data/starbucks.csv")
df

beverage_category                                    beverage  \
0                      coffee                               brewed coffee   
1                      coffee                               brewed coffee   
2                      coffee                               brewed coffee   
3                      coffee                               brewed coffee   
4     classic espresso drinks                                  caff latte   
..                        ...                                         ...   
237  frappuccino blended crme  strawberries  crme (without whipped cream)   
238  frappuccino blended crme        vanilla bean (without whipped cream)   
239  frappuccino blended crme        vanilla bean (without whipped cream)   
240  frappuccino blended crme        vanilla bean (without whipped cream)   
241  frappuccino blended crme        vanilla bean (without whipped cream)   

          beverage_prep  calories  total fat  trans fat  saturated fat  \
0                 Short         3        0.1        0.0            0.0   
1                  Tall         4        0.1        0.0            0.0   
2                Grande         5        0.1        0.0            0.0   
3                 Venti         5        0.1        0.0            0.0   
4     Short Nonfat Milk        70        0.1        0.1            0.0   
..                  ...       ...        ...        ...            ...   
237             Soymilk       320        3.2        0.4            0.0   
238    Tall Nonfat Milk       170        0.1        0.1            0.0   
239          Whole Milk       200        3.5        2.0            0.1   
240             Soymilk       180        1.5        0.2            0.0   
241  Grande Nonfat Milk       240        0.1        0.1            0.0   

     sodium  total carbohydrates  cholesterol  dietary fibre  sugars  protein  \
0         0                    5            0              0       0      0.3   
1         0                   10            0              0       0      0.5   
2         0                   10            0              0       0      1.0   
3         0                   10            0              0       0      1.0   
4         5                   75           10              0       9      6.0   
..      ...                  ...          ...            ...     ...      ...   
237       0                  250           67              1      64      5.0   
238       0                  160           39              0      38      4.0   
239      10                  160           39              0      38      3.0   
240       0                  160           37              1      35      3.0   
241       5                  230           56              0      55      5.0   

     vitamin a  vitamin c  calcium  iron  caffeine  
0            0          0        0   0.0     175.0  
1            0          0        0   0.0     260.0  
2            0          0        0   0.0     330.0  
3            0          0        2   0.0     410.0  
4           10          0       20   0.0      75.0  
..         ...        ...      ...   ...       ...  
237          6          8       20  10.0       0.0  
238          6          0       10   0.0       0.0  
239          6          0       10   0.0       0.0  
240          4          0       10   6.0       0.0  
241          8          0       15   0.0       0.0  

[242 rows x 18 columns]

In [11]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
df["calories"].sum()

46917

In [17]:
# how many different categories of beverages are there?
df["beverage_category"].value_counts()

classic espresso drinks             58
tazo tea drinks                     52
signature espresso drinks           40
frappuccino blended coffee          36
shaken iced beverages               18
frappuccino blended crme            13
frappuccino light blended coffee    12
smoothies                            9
coffee                               4
Name: beverage_category, dtype: int64

In [22]:
# what is the average # calories for each beverage category?
df.groupby("beverage_category")["calories"].mean()

beverage_category
classic espresso drinks             140.172414
coffee                                4.250000
frappuccino blended coffee          276.944444
frappuccino blended crme            233.076923
frappuccino light blended coffee    162.500000
shaken iced beverages               114.444444
signature espresso drinks           250.000000
smoothies                           282.222222
tazo tea drinks                     177.307692
Name: calories, dtype: float64

In [31]:
# what beverage preparation includes the most sugar on average?
df.groupby("beverage_prep")["sugars"].mean().sort_values(ascending = False)

beverage_prep
Whole Milk            55.687500
Venti Nonfat Milk     50.045455
Grande Nonfat Milk    38.615385
Soymilk               31.848485
2% Milk               30.980000
Tall Nonfat Milk      28.521739
Venti                 27.714286
Grande                20.000000
Short Nonfat Milk     17.000000
Tall                  14.714286
Short                  8.250000
Doppio                 0.000000
Solo                   0.000000
Name: sugars, dtype: float64

In [ ]:
# what is the average % daily value calcium content for each beverage?


In [ ]:
# It's bulking season. What drink should Naitian get so that he maximizes protein but minimizes calories?
# (you can use more than one line for this one)
# there are multiple valid approaches you can take for this (with different answers)
# I know that you want more calories for bulking season but whatever this is MDST, not Michigan Muscle Club okay


In [ ]:
# plot the distribution of the number of calories in drinks using matplotlib


In [ ]:
# plot the same distribution using seaborn. what about a density plot instead?


In [ ]:
# plot calories against total fat using seaborn


In [ ]:
# plot the distribution of calories in Short, Tall, Grande, and Venti drinks
# (you can use multiple lines for this)
# twist: you should also include the Nonfat Milk drinks that also have an associated size.

# you can decide how you want to visualize this. Colors? Small multiples? Density vs histogram?
# the starbucks is your oyster.
